### PR TITLE
ioTap method parameters rename, Jump to Counterpart enhancement and Omnis 10.1 JSON import fix

### PR DESCRIPTION
**Pull request by Frogli**
This pull request contains three things.
- ioTap method parameters rename: pVar1 and pVar2 parameters renamed to pHave and pWant
- Jump to Counterpart enhancement: This function can also lets you jump between integration tests if there is only a integration test for that method. If both unit and integration test exist it jumps to the unittest. If none of them exist the changed function returns the potential unit test name.
- Last but not least a Omnis 10.1 JSON import fix. With Omnis 10.1 a property was changes from a integer to a string value.

### CODE REVIEW

**Comment by barkingfoodog** [comment]
Looks great, thanks for adding the new functionality and updating to 10.1.

Is the `lib/10.1/omnistap copy.lbs` meant to be included?

**Comment by Frogli** [comment]
ah ok, no that one was not supposed to be commited. Shall I create a new Pull request?

**Comment by barkingfoodog** [comment]
No worries! I thought it might be a stowaway.

Can you delete it from this branch and push again? That will update this PR.

**Comment by Frogli** [comment]
Branch updated 👍

**Comment by barkingfoodog** [comment]
Great! Thanks again for the contribution!

**Pull request merged**
