### PR TITLE
Removed lowercasing on the list wgOmnisTap.ilLibrary and reference to suran_vcs

### PR DESCRIPTION
**Pull request by Frogli**
wgOmnisTap.$_loadLibraries:
* Removed the upp2lowercasing on the list ilLibraries. This way the libraries doe not have to be lowercase to run the tests. The method  does a  on the  which is not lowercase.
* Also removed a reference on line 14 to suran_vcs

### CODE REVIEW

**Comment by barkingfoodog** [comment]
Thank you for the contribution! Would you please run a new export to JSON and update the `src/omnistap` files? This should show the code changes in the PR.

I ran a local JSON export from your 8.1 library, diff'd it with master, and it looks good. I'll merge this in once you add the src.

**Comment by Frogli** [comment]
Sure, I will do. I only do not see a src folder with the JSON file in you repository. Is that correct?

**Comment by barkingfoodog** [comment]
Mea culpa! I forgot to add the src. It should be available in master now.

**Comment by Frogli** [comment]
Tnx, I have added my version of the sources files.

**Pull request merged**
