### PR TITLE
Added public method injection for testing private methods

### PR DESCRIPTION
**Pull request by Frogli**
ogTAPSuper has a method $insertForwardingmethod which injects a public method of a private method to the instance of an object. This way the private can be tested without being forced to make the method public and use a code convention to distinguish the public methods from the private ones. 
eg:

```
Do $objects.oTree.$newref() Returns lorTreeRef
Do $cinst.$insertForwardingMethod(lorTreeRef,'isTree')

Do lorTreeRef.$isTree() Return lbActualValue
; Do some tests on the lbActualValue
```

### CODE REVIEW

**Comment by barkingfoodog** [comment]
Thank you for adding this! I noticed `prObject` on `ogTAPSuper.$insertForwardingMethod` has a subtype that might be from one of your libraries. I was going to suggest you remove it, but what do you think about changing that parameter to field reference  so we could pass either an object ref, item ref to a window/menu/menu/toolbar, or a list or row defined from a table class to allow forwarding public methods on those?

**Comment by Frogli** [comment]
Yep nice suggestion I have committed it.

**Comment by barkingfoodog** [comment]
Do you mind to add documentation to wiki for this? There's some mention on the [Test classes and methods](https://github.com/suransys/omnistap/wiki/Test-Classes-and-Methods#naming-1) page about testing local methods that could use a reference `$insertForwardingMethod`.

**Comment by Frogli** [comment]
Yes that was I planning to do. Only how do I create a pull request button on that git. Do know how I can do that? I vaguely remember you told me before, but I forgot... 😊

**Comment by barkingfoodog** [comment]
Looks like making a PR to a wiki [isn't possible](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github). I can make you a collaborator, but that's probably too broad of access since this repository it under my company's account.

I'll go ahead and update the wiki. It's no problem at all. :)

**Comment by Frogli** [comment]
oh wow tnx, you are too kind!

**Comment by barkingfoodog** [comment]
No worries! I added a section documenting `$insertForwardingMethod` [here](https://github.com/suransys/omnistap/wiki/Mocking#calling-private-methods). I also added a suggestion to use `$insertForwardingMethod` when testing private methods [here](https://github.com/suransys/omnistap/wiki/Test-Classes-and-Methods#naming-1). Let me know if you'd like any changes to these and I'll be happy to make them.

**Comment by Frogli** [comment]
Tnx again for adding the documentation. No addition to be added 😉

**Pull request merged**
